project:
  type: website

website:
  title: "Perceptual"
  navbar:
    toggle-position: right
    search: false
    background: dark
    left:
      - href: "about/index.qmd"
        text: About
      - href: "join/index.qmd"
        text: Join
      - href: "team/index.qmd"
        text: Team
format:
  html:
    theme:
      - darkly
      - custom.scss
    toc: false
    page-layout: article
    grid:
      body-width: 1200px
      margin-width: 250px



