project:
  type: website

website:
  title: "Perceptual"
  # navbar:
  #   logo: assets/logo-dark.png
  #   background: "#000000"
  #   brand: true
  #   search: false
  #   left:
  #     - href: about.qmd
  #       text: About
  #     - href: about.qmd
  #       text: Components
  #     - href: about.qmd
  #       text: Jobs
format:
  html:
    theme:
      - litera
      - brand
      - custom-theme.scss
    toc: true
    grid:
      body-width: 1000px
      margin-width: 250px



