project:
  type: website

website:
  title: "Perceptual"
  navbar:
    search: false
    # logo: assets/logo-dark.png
    background: dark
    left:
      - href: "join/index.qmd"
        text: Join
      - href: "platform/index.qmd"
        text: Platform
      - href: "team/index.qmd"
        text: Team

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: styles.css
    toc: false
    page-layout: article
    grid:
      body-width: 1400px
      margin-width: 250px



